apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
      ##################### Grafana Configuration Example #####################
    #
    # Everything has defaults so you only need to uncomment things you want to
    # change
    # possible values : production, development
    ; app_mode = production
    # instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
    ; instance_name = ${HOSTNAME}
    #################################### Paths ####################################
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    #################################### Server ####################################
    [server]
    # Protocol (http, https, socket)
    protocol = http
    # The ip address to bind to, empty will bind to all interfaces
    http_addr =
    # The http port  to use
    http_port = 3000
    # The public facing domain name used to access grafana from a browser
    domain = MINIKUBE_IP
    #################################### Database ####################################
    [database]
    # You can configure the database connection by specifying type, host, name, user and password
    # as seperate properties or as on string using the url propertie.
    # Either "mysql", "postgres" or "sqlite3", it's your choice
    type = influxdb
    host = http://influxdb:8086
    name = telegraf
    user = admin
    password = 1234
    #################################### Session ####################################
    [session]
    # Either "memory", "file", "redis", "mysql", "postgres", default is "file"
    ;provider = file
    # Provider config options
    # memory: not have any config yet
    # file: session dir path, is relative to grafana data_path
    # redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
    # mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
    # postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
    ;provider_config = sessions
    # Session cookie name
    ;cookie_name = grafana_sess
    # If you use session in https only, default is false
    ;cookie_secure = false
    # Session life time, default is 86400
    ;session_life_time = 86400
    #################################### Data proxy ###########################
    [dataproxy]
    # This enables data proxy logging, default is false
    ;logging = false
    #################################### Analytics ####################################
    [analytics]
    # Server reporting, sends usage counters to stats.grafana.org every 24 hours.
    # No ip addresses are being tracked, only simple counters to track
    # running instances, dashboard and error counts. It is very helpful to us.
    # Change this option to false to disable reporting.
    ;reporting_enabled = true
    # Set to false to disable all checks to https://grafana.net
    # for new vesions (grafana itself and plugins), check is used
    # in some UI views to notify that grafana or plugin update exists
    # This option does not cause any auto updates, nor send any information
    # only a GET request to http://grafana.com to get latest versions
    ;check_for_updates = true
    # Google Analytics universal tracking code, only enabled if you specify an id here
    ;google_analytics_ua_id =
    #################################### Security ####################################
    [security]
    # default admin user, created on startup
    admin_user = $GF_ADMIN_USER
    # default admin password, can be changed before first start of grafana,  or in profile settings
    admin_password = $GF_ADMIN_PASSWORD
    #################################### Users ####################################
    #################################### Anonymous Auth ##########################
    #################################### Github Auth ##########################
    #################################### Google Auth ##########################
    #################################### Generic OAuth ##########################
    #################################### Grafana.com Auth ####################
    #################################### Auth Proxy ##########################
    #################################### Basic Auth ##########################
    #################################### Auth LDAP ##########################
    #################################### SMTP / Emailing ##########################
    #################################### Logging ##########################
    #################################### AMQP Event Publisher ##########################
    #################################### Dashboard JSON files ##########################
    [dashboards.json]
    ;enabled = false
    ;path = /var/lib/grafana/dashboards
    #################################### Alerting ############################
    #################################### Internal Grafana Metrics ##########################
    #################################### Grafana.com integration  ##########################
    # Url used to to import dashboards directly from Grafana.com
    [grafana_com]
    ;url = https://grafana.com
    #################################### External image storage ##########################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
	  app: grafana
  template:
	metadata:
	  labels:
	    app: grafana
	spec:
	  containers:
	  - name: grafana
	    image: grafana
		imagePullPolicy: Never
		envFrom:
		- secretRef:
		    name: grafana-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
