apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      orgId: 1
      url: http://influxdb:8086
      user: admin
      password: 1234
      database: telegraf

  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'influxdb'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      options:
        path: /usr/share/grafana/public/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-config-volume
          subPath: datasources.yaml
          mountPath: /usr/share/grafana/conf/provisioning/datasources/datasources.yaml
          readOnly: true
        - name: grafana-config-volume
          subPath: dashboards.yaml
          mountPath: /usr/share/grafana/conf/provisioning/dashboards/dashboards.yaml
          readOnly: true
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana
