apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb-config
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      war-dir = "/var/lib/influxdb/wal"
    [http]
      enabled = true
      bind-address = "0.0.0.0:8086"
      log-enabled = true
    [admin]
      enabled = true
      bind-address = "0.0.0.0:8083"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: influxdb-secret
        ports:
        - containerPort: 8086
          name: influxdb-data
        - containerPort: 8083
          name: influxdb-admin
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
        - name: influxdb-config-volume
          subPath: influxdb.conf
          mountPath: /etc/influxdb.conf
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: influxdb-config-volume
        configMap:
          name: influxdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: influxdb-data
    port: 8086
    targetPort: 8086
  - name: influxdb-admin
    port: 8083
    targetPort: 8083

